services:
  ejison:
    build: .
    image: deshrit/ejison
    container_name: ejison
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    working_dir: /ejison
    volumes:
      - ./:/ejison
